name: CI Test Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    name: Test - Node v${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4

        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - name: Build Core Class Fixer
        run: pnpm --filter=@tailwindcss/class-fixer run build

      - name: Build CLI Fixer
        run: pnpm --filter=@tailwindcss/cli-fixer run build

      - name: Build Language Service & Server
        run: |
          pnpm --filter=@tailwindcss/language-syntax run build
          pnpm --filter=@tailwindcss/language-service run build

      - name: Check VS Code Extension Types & Build
        run: pnpm --filter=tailwindcss-intellisense-fix run build

      - name: Run Class Fixer & CLI Tests
        run: |
          pnpm --filter=@tailwindcss/class-fixer run test
          pnpm --filter=@tailwindcss/cli-fixer run test

      - name: Run Language Syntax & Service Tests
        run: |
          pnpm --filter=@tailwindcss/language-syntax run test
          pnpm --filter=@tailwindcss/language-service run test

      - name: Run LSP Code Actions Integration Tests
        run: pnpm --filter=@tailwindcss/language-server test run tests/code-actions/

      - name: Package VSIX Extension Verification
        run: pnpm --filter=tailwindcss-intellisense-fix run package


